name: Build and publish

on:
    push:
        tags:
            - "*"

env:
    SQLITE_RELEASE_YEAR: "2021"
    SQLITE_VERSION: "3340100"

jobs:
    publish-windows:
        name: Publish for Windows
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2

            - name: Download sources
              shell: bash
              run: |
                  curl -L http://sqlite.org/$SQLITE_RELEASE_YEAR/sqlite-amalgamation-$SQLITE_VERSION.zip --output src.zip
                  7z x src.zip

            - name: Compile sources
              run: |
                  mkdir dist
                  gcc.exe -I. src/shell.c src/sqlite3.c -o dist/sqlite3.exe \
                    -DSQLITE_THREADSAFE=0 \
                    -DSQLITE_ENABLE_EXPLAIN_COMMENTS \
                    -DSQLITE_INTROSPECTION_PRAGMAS \
                    -DSQLITE_ENABLE_UNKNOWN_SQL_FUNCTION \
                    -DSQLITE_ENABLE_STMTVTAB \
                    -DSQLITE_ENABLE_DBPAGE_VTAB \
                    -DSQLITE_ENABLE_DBSTAT_VTAB \
                    -DSQLITE_ENABLE_OFFSET_SQL_FUNC \
                    -DSQLITE_ENABLE_JSON1 \
                    -DSQLITE_ENABLE_RTREE \
                    -DSQLITE_ENABLE_FTS4 \
                    -DSQLITE_ENABLE_FTS5

            - name: Upload binaries to release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: dist/sqlite3.exe
                  asset_name: sqlite3.exe
                  tag: ${{ github.ref }}
